name: Test

on:
  push:
  schedule:
    - cron: '0 17 1,15 * *'

jobs:

  commitlint:
    name: Check commit message
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      # https://github.com/conda-incubator/setup-miniconda
      - name: Setup mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Expire cache weekly
        run: echo "DATE=$(date +'%V')" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache@v2
        env:
          CACHE_VERSION: 0
        with:
          path: /usr/share/miniconda3/envs/test
          key: conda-${{ runner.os }}-${{ hashFiles('conda/test.yml') }}-${{ env.DATE }}-${{ env.CACHE_VERSION }}
        id: cache

      - name: Install test dependencies
        env:
          PYROSETTA_USER: ${{ secrets.PYROSETTA_USER }}
          PYROSETTA_PASS: ${{ secrets.PYROSETTA_PASS }}
        run: |
          #mamba config --add channels https://$PYROSETTA_USER:$PYROSETTA_PASS@conda.graylab.jhu.edu
          mamba env update --file conda/test.yml --name test
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run test suite
        run: |
          pytest bin

